package com.pluralsight.NorthwindTradersSpringBoot;

import com.pluralsight.NorthwindTradersSpringBoot.Dao.ProductDao;
import com.pluralsight.NorthwindTradersSpringBoot.models.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Scanner;

@Component
public class NorthwindApplication implements CommandLineRunner {

    @Autowired
    private ProductDao productDao;

    @Override
    public void run(String... args) throws Exception {
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println("\n--- Northwind Traders ---");
            System.out.println("1) List Products");
            System.out.println("2) Add Product");
            System.out.println("0) Exit");
            System.out.print("Select an option: ");

            int choice = scanner.nextInt();
            scanner.nextLine(); // Consume newline

            switch (choice) {
                case 1:
                    listAllProducts();
                    break;
                case 2:
                    addNewProduct(scanner);
                    break;
                case 0:
                    System.out.println("Exiting application.");
                    return;
                default:
                    System.out.println("Invalid option, please try again.");
            }
        }
    }

    private void listAllProducts() {
        System.out.println("\n--- All Products ---");
        List<Product> products = productDao.getAll();
        for (Product product : products) {
            System.out.printf("ID: %-5d Name: %-40s Category: %-20s Price: $%.2f%n",
                    product.getProductId(),
                    product.getName(),
                    product.getCategory(),
                    product.getPrice());
        }
    }

    private void addNewProduct(Scanner scanner) {
        System.out.println("\n--- Add New Product ---");
        System.out.print("Enter product name: ");
        String name = scanner.nextLine();

        System.out.print("Enter product price: ");
        double price = scanner.nextDouble();
        scanner.nextLine(); // Consume newline

        // Creating a new product object. The ID will be auto-generated by the database.
        // The category is hardcoded in the DAO for simplicity.
        Product newProduct = new Product();
        newProduct.setName(name);
        newProduct.setPrice(price);

        productDao.add(newProduct);
        System.out.println("Product added successfully!");
    }
}